#!/bin/bash
cd -- $(dirname "${BASH_SOURCE[0]}")

host="cyrille@192.168.13.1"
remote_path="standalone/"
ssh_cmd="ssh -qo StrictHostKeyChecking=no"  # all the robots share the same local IP

sync_files() {
  rsync -ac --info=NAME -e "${ssh_cmd}" --delete \
    compose.yaml config \
    "${host}:${remote_path}"
}

echo "Sync files..."
sync_files

echo
echo "Listen local changes and send them to '${host}:${remote_path}'"
echo "Listening..."

while inotifywait -rqq -emodify -ecreate -emove -edelete "." ; do
  echo -e "\e[1m$(date +%X) change detected, updating remote\e[0m"
  sync_files
done
